# -*- coding: utf-8 -*-
"""
Created on Sat Aug  1 17:40:14 2015

@author: Brahm
"""
import os
import numpy as np
os.chdir('//Users//Tommy//Desktop//Concordance_V1//Book_arrays')

Genesis = np.load('Genesis_V1.npy')
Exodus = np.load('Exodus_V1.npy')
Leviticus = np.load('Leviticus_V1.npy')
Numbers = np.load('Numbers_V1.npy')
Deuteronomy = np.load('Deuteronomy_V1.npy')
Joshua = np.load('Joshua_V1.npy')
Judges = np.load('Judges_V1.npy')
Ruth = np.load('Ruth_V1.npy')
I_Samuel = np.load('I_Samuel_V1.npy')
II_Samuel = np.load('II_Samuel_V1.npy')
I_Kings = np.load('I_Kings_V1.npy')
II_Kings = np.load('II_Kings_V1.npy')
I_Chronicles = np.load('I_Chronicles_V1.npy')
II_Chronicles = np.load('II_Chronicles_V1.npy')
Ezra = np.load('Ezra_V1.npy')
Nehemiah = np.load('Nehemiah_V1.npy')
Esther = np.load('Esther_V1.npy')
Job = np.load('Job_V1.npy')
Psalms = np.load('Psalms_V1.npy')
Proverbs = np.load('Proverbs_V1.npy')
Ecclesiastes = np.load('Ecclesiastes_V1.npy')
Song_of_Solomon = np.load('Song_of_Solomon_V1.npy')
Isaiah = np.load('Isaiah_V1.npy')
Jeremiah = np.load('Jeremiah_V1.npy')
Lamentations = np.load('Lamentations_V1.npy')
Ezekiel = np.load('Ezekiel_V1.npy')
Daniel = np.load('Daniel_V1.npy')
Hosea = np.load('Hosea_V1.npy')
Joel = np.load('Joel_V1.npy')
Amos = np.load('Amos_V1.npy')
Obadiah = np.load('Obadiah_V1.npy')
Jonah = np.load('Jonah_V1.npy')
Micah = np.load('Micah_V1.npy')
Nahum = np.load('Nahum_V1.npy')
Habakkuk = np.load('Habakkuk_V1.npy')
Zephaniah = np.load('Zephaniah_V1.npy')
Haggai = np.load('Haggai_V1.npy')
Zechariah = np.load('Zechariah_V1.npy')
Malachi = np.load('Malachi_V1.npy')

Matthew = np.load('Matthew_V1.npy')
Mark = np.load('Mark_V1.npy')
Luke = np.load('Luke_V1.npy')
John = np.load('John_V1.npy')
Acts = np.load('Acts_V1.npy')
Romans = np.load('Romans_V1.npy')
I_Corinthians = np.load('I_Corinthians_V1.npy')
II_Corinthians = np.load('II_Corinthians_V1.npy')
Galatians = np.load('Galatians_V1.npy')
Ephesians = np.load('Ephesians_V1.npy')
Philippians = np.load('Philippians_V1.npy')
Colossians = np.load('Colossians_V1.npy')
I_Thessalonians = np.load('I_Thessalonians_V1.npy')
II_Thessalonians = np.load('II_Thessalonians_V1.npy')
I_Timothy = np.load('I_Timothy_V1.npy')
II_Timothy = np.load('II_Timothy_V1.npy')
Titus = np.load('Titus_V1.npy')
Philemon = np.load('Philemon_V1.npy')
Hebrews = np.load('Hebrews_V1.npy')
James = np.load('James_V1.npy')
I_Peter = np.load('I_Peter_V1.npy')
II_Peter = np.load('II_Peter_V1.npy')
I_John = np.load('I_John_V1.npy')
II_John = np.load('II_John_V1.npy')
III_John = np.load('III_John_V1.npy')
Jude = np.load('Jude_V1.npy')
Revelation = np.load('Revelation_V1.npy')

Old_Testament = {'Genesis':Genesis , 'Exodus':Exodus , 'Leviticus':Leviticus , 'Numbers':Numbers , 'Deuteronomy':Deuteronomy , 'Joshua':Joshua , 'Judges':Judges , 'Ruth':Ruth , 'I_Samuel':I_Samuel , 'II_Samuel':II_Samuel , 'I_Kings':I_Kings , 'II_Kings':II_Kings , 'I_Chronicles':I_Chronicles , 'II_Chronicles':II_Chronicles , 'Ezra':Ezra , 'Nehemiah':Nehemiah , 'Esther':Esther , 'Job':Job , 'Psalms':Psalms , 'Proverbs':Proverbs , 'Ecclesiastes':Ecclesiastes , 'Song_of_Solomon':Song_of_Solomon , 'Isaiah':Isaiah , 'Jeremiah':Jeremiah , 'Lamentations':Lamentations , 'Ezekiel':Ezekiel , 'Daniel':Daniel , 'Hosea':Hosea , 'Joel':Joel , 'Amos':Amos , 'Obadiah':Obadiah , 'Jonah':Jonah , 'Micah':Micah , 'Nahum':Nahum , 'Habakkuk':Habakkuk , 'Zephaniah':Zephaniah , 'Haggai':Haggai , 'Zechariah':Zechariah , 'Malachi':Malachi}
New_Testament = {'Matthew':Matthew , 'Mark':Mark , 'Luke':Luke , 'John':John , 'Acts':Acts , 'Romans':Romans , 'I_Corinthians':I_Corinthians , 'II_Corinthians':II_Corinthians , 'Galatians':Galatians , 'Ephesians':Ephesians , 'Philippians':Philippians , 'Colossians':Colossians , 'I_Thessalonians':I_Thessalonians , 'II_Thessalonians':II_Thessalonians , 'I_Timothy':I_Timothy , 'II_Timothy':II_Timothy , 'Titus':Titus , 'Philemon':Philemon , 'Hebrews':Hebrews , 'James':James , 'I_Peter':I_Peter , 'II_Peter':II_Peter , 'I_John':I_John , 'II_John':II_John , 'III_John':III_John , 'Jude':Jude , 'Revelation':Revelation}
Bible = {'Old_Testament':Old_Testament , 'New_Testament'}
#print([key for key,value in sentences.items()])